### ISSUE TITLE
Firefox - backspace, tab, etc. key events not being read

### ISSUE THREAD

**Issue by ChaudhryAtif** [awerlang/angular-easy-masks#21]
Some key events (like tab, backspace) are not being read in Firefox. They seem to be working fine in Chrome. This can be seen for allowInvalid and Simple mask scenarios on the [demo](http://blog.werlangtecnologia.com.br/angular-easy-masks/examples/) page.

Issue could be due to using [keypress](https://github.com/awerlang/angular-easy-masks/blob/master/release/angular-easy-masks.js#L114) instead of keydown.

Example StackOverflow issue [here](https://stackoverflow.com/questions/4843472).

**Comment by awerlang** [comment]
We've tried `keyup` before which caused other issues. I don't remember if `keydown` was tried, maybe it would work better. Or just work-around Firefox, as it's an issue 17 years old (!) so will never get fixed.

Prior work: #13, #17

**Comment by awerlang** [comment]
`keydown` lets you tab though if the field is non-empty and there's a selection. Otherwise you'll get stuck in the field.

I'll prefer keeping `keypress` as it's the standard way to deal with printable characters, so we won't break other browsers just because Firefox. Then ignoring all keys below 48, it seems to work. There's a few other mildly annoying issues, non-related to this one, so I get some time next week and look carefully to see what else needs improvement.

```
diff --git a/src/directive.js b/src/directive.js
index de60898..d25be69 100644
--- a/src/directive.js
+++ b/src/directive.js
@@ -47,12 +47,12 @@ function wtEasyMask($parse, $log, easyMask) {
             });

             element.on('keypress', function (event) {
-                var keyIsEnter = event.which === 13;
-                if (keyIsEnter) return;
-
+                var keyIsNonPrintable = event.which < 48;
                 var keyIsSpace = event.which === 32;
                 if (keyIsSpace) {
                     event.preventDefault();
+                } else if (keyIsNonPrintable) {
+                    return;
                 } else if (element.prop('selectionStart') === element.prop('selectionEnd')) {
                     var currentValue = element.val();
                     var futureValue = currentValue.substring(0, element.prop('selectionStart'))
```
